## COMPILER :
 : reads the program completely at one


## INTERPRETER
: reads aprogram line by line, if line 1 had error interpreter will not move onto line 2

# NUMPY

In [4]:
## creating numpy/nd arrays
import numpy as np

In [6]:
arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [8]:
type(arr)

numpy.ndarray

In [10]:
## to check dimensions of an array
print(arr.ndim)

1


In [12]:
arr1 = np.array([[1,2],[2,3]])
print(arr1.ndim)

2


In [14]:
arr2 = np.array([[1,2,3,4],[5,6,7,8]])

In [16]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [18]:
arr3 = np.array([[1,2,3],[4,5,6],[7,8,9]])

In [20]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [22]:
print(arr3.ndim)

2


In [24]:
arr4 = np.zeros((2,3))
arr4

array([[0., 0., 0.],
       [0., 0., 0.]])

In [26]:
arr5 = np.ones((2,3))
arr5

array([[1., 1., 1.],
       [1., 1., 1.]])

In [28]:
arr5 = np.identity((4))

In [30]:
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [32]:
arr6 = np.linspace(10,20,30)
arr6

array([10.        , 10.34482759, 10.68965517, 11.03448276, 11.37931034,
       11.72413793, 12.06896552, 12.4137931 , 12.75862069, 13.10344828,
       13.44827586, 13.79310345, 14.13793103, 14.48275862, 14.82758621,
       15.17241379, 15.51724138, 15.86206897, 16.20689655, 16.55172414,
       16.89655172, 17.24137931, 17.5862069 , 17.93103448, 18.27586207,
       18.62068966, 18.96551724, 19.31034483, 19.65517241, 20.        ])

In [34]:
arr7 = np.arange(10,20,2)
arr7

array([10, 12, 14, 16, 18])

In [36]:
arr7 = np.arange(10,20,3)
arr7

array([10, 13, 16, 19])

In [38]:
 arr7 = np.arange(10,30,4)
arr7

array([10, 14, 18, 22, 26])

In [40]:
arr5

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [42]:
arr7

array([10, 14, 18, 22, 26])

In [44]:
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [46]:
arr8 = arr3.copy()
arr8

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [48]:
arr9 = np.array([[[1,3],[3,4]],[[5,6],[6,7]]])
print(arr9)
print(arr9.ndim)

[[[1 3]
  [3 4]]

 [[5 6]
  [6 7]]]
3


In [50]:
arr10 = np.array([[[[3,4],[5,6]]]])
print(arr10)
print(arr10.ndim)
print(arr10.shape)

[[[[3 4]
   [5 6]]]]
4
(1, 1, 2, 2)


In [52]:
arr10.size #number of elements in an array

4

In [54]:
arr10.itemsize

4

In [56]:
print(arr10)
print(arr10.dtype)

[[[[3 4]
   [5 6]]]]
int32


In [164]:
arr4.astype('float')

array([[0., 0., 0.],
       [0., 0., 0.]])

In [166]:
lista=range(100)
arr11 = np.arange(100)

In [168]:
import sys
print(sys.getsizeof(12)*len(lista))

2800


In [170]:
print(arr11.itemsize*arr11.size)

400


## INDEXING SLICING AND ITERATION

In [175]:
import numpy as np

In [177]:
arr = np.arange(24).reshape(6,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [179]:
## arr[(rows),(cols)]
arr[2:4,1:3]

array([[ 9, 10],
       [13, 14]])

In [181]:
arr[4:6,0:2]

array([[16, 17],
       [20, 21]])

In [183]:
arr[2:6,1:3]

array([[ 9, 10],
       [13, 14],
       [17, 18],
       [21, 22]])

In [185]:
# make github acc and download "git for windows"

In [187]:
# sajid majeed

In [189]:
arr2 = np.arange(30).reshape(5,6)
print(arr2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]]


In [191]:
# retrieve row number 3 and 4
arr2[2:4]

array([[12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23]])

In [193]:
# to retrieve all rows
arr2[:]

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29]])

In [195]:
# to retrieve specific values
arr2[2:4,1:5]

array([[13, 14, 15, 16],
       [19, 20, 21, 22]])

In [197]:
arr2[0:4,1:4]

array([[ 1,  2,  3],
       [ 7,  8,  9],
       [13, 14, 15],
       [19, 20, 21]])

In [199]:
arr2[0:4,1:5]

array([[ 1,  2,  3,  4],
       [ 7,  8,  9, 10],
       [13, 14, 15, 16],
       [19, 20, 21, 22]])

In [201]:
# to skip a few columns
# arr2[:,1::2]
arr2[0:5,1:6:2]


array([[ 1,  3,  5],
       [ 7,  9, 11],
       [13, 15, 17],
       [19, 21, 23],
       [25, 27, 29]])

In [203]:
arr2[0:6:2,0:5]

array([[ 0,  1,  2,  3,  4],
       [12, 13, 14, 15, 16],
       [24, 25, 26, 27, 28]])

In [205]:
arr2.size

30

In [207]:
arr2.itemsize #tells what memory do elements store i.e 4 bytes

4

In [209]:
arr2.shape

(5, 6)

In [211]:
arr2.ndim #dimensions

2

In [213]:
# for iterator(i) in iterable(array)
for i in arr2:
    print(i)

[0 1 2 3 4 5]
[ 6  7  8  9 10 11]
[12 13 14 15 16 17]
[18 19 20 21 22 23]
[24 25 26 27 28 29]


In [215]:
# apply filter on every pixel of the image
for i in np.nditer(arr2):
    print(i)
    # nditer or nd iterator reads our array/image pixel by pixel i.e gives information ofevery pixel or element

0
1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21
22
23
24
25
26
27
28
29


## NUMPY OPERATIONS:

In [218]:
new_arr1 = np.array([1,2,3,4,5,6])
new_arr2 = np.array([4,5,6,7,8,9])
print(new_arr1)
print(new_arr2)

[1 2 3 4 5 6]
[4 5 6 7 8 9]


In [220]:
# Addition
print(new_arr1 + new_arr2)

[ 5  7  9 11 13 15]


In [222]:
sum_arr = new_arr1 + new_arr2
print(sum_arr)

[ 5  7  9 11 13 15]


In [224]:
## Subtraction
print(new_arr1 - new_arr2)

[-3 -3 -3 -3 -3 -3]


In [226]:
# Multiplication
sum_arr = new_arr1 * new_arr2
print(sum_arr)

[ 4 10 18 28 40 54]


In [228]:
# multiply by 2
print(new_arr1*2)

[ 2  4  6  8 10 12]


In [230]:
# power of 2
print(new_arr1**2)

[ 1  4  9 16 25 36]


In [232]:
# conditional statements
# checks every value
new_arr1>3

array([False, False, False,  True,  True,  True])

In [234]:
# conditional statements
# checks every value
new_arr1>=3

array([False, False,  True,  True,  True,  True])

In [236]:
new_arr3 = np.arange(6).reshape(2,3)
new_arr4 = np.arange(6).reshape(3,2)
print(new_arr3)
print(new_arr4)

[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]


In [238]:
new_arr3*new_arr4
#gives error bcz of different shapes i.e rows and colums
# multiplication is only possible if m*n = m*n 
# but numpy arrays work differently
# if we want to multiply in numpy we taake dot product

ValueError: operands could not be broadcast together with shapes (2,3) (3,2) 

In [240]:
# to take dot product of 3 and 4 and store it ina new variable 
new_arr5 = new_arr3.dot(new_arr4)
print(new_arr5)

[[10 13]
 [28 40]]


In [242]:
new_arr5.max()

40

In [244]:
new_arr5.min()

10

In [246]:
# to retrieve minimum in both rows anddcolums as a set
new_arr5.min(axis=0)

array([10, 13])

In [248]:
# to retrieve maximum in both rows anddcolums as a set
new_arr5.max(axis=0)

array([28, 40])

In [250]:
# to retrieve minimum in both rows anddcolums as a set
new_arr4.min(axis=0)

array([0, 1])

In [252]:
# to retrieve minimum in both rows anddcolums as a set
new_arr5.min(axis=1)

array([10, 28])

In [254]:
# mean
#median
# standard deviation
print(new_arr5.mean())
print(new_arr5.std())

22.75
12.07010770457331


In [256]:
new_arr5.ndim

2

In [258]:
# reshaping numpy arrays
print(new_arr5)
print(new_arr5.ndim)

[[10 13]
 [28 40]]
2


In [260]:
# convert higher dimensional into lower dimension or one dimension
new_arr6 =new_arr5.ravel()
print(new_arr6)
print(new_arr6.ndim)

[10 13 28 40]
1


In [262]:
print(new_arr5)
new_arr5.transpose()

[[10 13]
 [28 40]]


array([[10, 28],
       [13, 40]])

In [268]:
new_arr6 = np.arange(4).reshape(2,2)
new_arr6

array([[0, 1],
       [2, 3]])

In [270]:
# stacking
np.hstack((new_arr5,new_arr6))

array([[10, 13,  0,  1],
       [28, 40,  2,  3]])

In [272]:
new_arr6 = np.arange(4).reshape(2,2)
print(new_arr6)

[[0 1]
 [2 3]]


In [274]:
np.hstack((new_arr5,new_arr6)) # horizontal

array([[10, 13,  0,  1],
       [28, 40,  2,  3]])

In [276]:
new_arr7 = np.array([1,2,3,4,5,6,7,8])
new_arr8 = np.array([4,5,6,7,8,9,10,11])
print(new_arr7)
print(new_arr8)

[1 2 3 4 5 6 7 8]
[ 4  5  6  7  8  9 10 11]


In [278]:
np.vstack((new_arr5,new_arr6)) # vertical

array([[10, 13],
       [28, 40],
       [ 0,  1],
       [ 2,  3]])

In [280]:
# split
np.hsplit(new_arr5,2)

[array([[10],
        [28]]),
 array([[13],
        [40]])]

In [282]:
# split
np.vsplit(new_arr5,2)

[array([[10, 13]]), array([[28, 40]])]